project:
  title: "Julia for biodiversity/AI workshop"
  output-dir: docs
  render: 
    - slides.qmd

toc: false
number-sections: false

execute: 
  freeze: true

format:
    revealjs:
        slide-number: true
        logo: assets/poisotlab.png
        theme: assets/theme.scss
        code-line-numbers: false
        code-copy: false
        footer: "CC BY 4.0 - Timothée Poisot"
        output-file: "index"
        output-format: "html"