project:
  title: "Julia for biodiversity/AI workshop"
  output-dir: docs
  render: 
    - slides.qmd

toc: false
number-sections: false

format:
    revealjs:
        slide-number: true
        logo: assets/geobon.png
        theme: default
        highlight-style: a11y
        footer: "CC BY 4.0 - Timothée Poisot"